# Site settings
title: Greenspace.Group
email: MarkBruns@MarkBruns.com
description: Volunteer, Enjoy, Contribute to SHARING Your Local Greenspaces
twitter_username: MarkBruns
github_username:  GreenspaceGroup

# Build settings
markdown: kramdown
