# Site settings
title: Greenspace.Group
email: MarkBruns@MarkBruns.com
description: Voluntary Involvement In Developing Local Greenspaces
twitter_username: MarkBruns
github_username:  GreenspaceGroup

# Build settings
markdown: kramdown
